---
twist_mux:
  ros__parameters:
    use_stamped: false
    topics:
      navigation:
        topic: cmd_vel
        timeout: 0.5
        priority: 20
      joystick:
        topic: cmd_vel_joy
        timeout: 0.5
        priority: 21
      keyboard:
        topic: cmd_vel_key
        timeout: 0.5
        priority: 22
